package org.hinz.euler

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

object Solution2 {

  def fibs(n1:Int = 0, n2:Int = 1): Stream[Int] = Stream.cons(n1 + n2, fibs(n2, n1 + n2))

  def calc = fibs().takeWhile(_ < 4000000).filter(_ % 2 == 0).reduceLeft(_ + _)

  def run = {
      println(calc)
  }

}
